version: '2.3'
services:
  server:
    image: yuiskw/python-rest-apis-tornado:dev
    container_name: server
    restart: always
    ports:
     - "8080:8080"
    environment:
      - NUM_WORKERS=2
      - MAX_REQUESTS=10000
    volumes:
      - ~/.config/:/root/.config:rw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0/healthcheck"]  # TODO update url
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 40s
