name: python-rest-apis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6.5
  - cython=0.28.5
  - flake8=3.5.0
  - flask=1.0.2
  - flask-restful=0.3.6
  - numpy=1.15.0
  - openblas=0.2.20
  - openssl=1.0.2p
  - pytest=3.8.2
  - python-json-logger=0.1.9
  - requests=2.19.1
  - scipy=1.1.0
  - uwsgi=2.0.17.1
  - tornado=5.1.1
  - cherrypy=18.0.1
  - nltk=3.3.0
  - scikit-learn=0.20.0
  - tensorflow=1.12.0
  - pillow=5.3.0
  - pip:
    - google-cloud-storage==1.13.0
